Add flags to improve hparams_search for Release 1.4.0
ashleve/lightning-hydra-template pull request #360
Opened 2022-06-26 04:04 UTC by yipliu

Hi,

I made a new PR for [release/1.4.0](https://github.com/ashleve/lightning-hydra-template/tree/release/1.4)

I remove this [link](https://github.com/facebookresearch/hydra/blob/8b9ce30802165c1b24dbf4e513eb78d8ca8cacd6/plugins/hydra_optuna_sweeper/hydra_plugins/hydra_optuna_sweeper/config.py#L144) because it is too long.

2022-06-26 04:19 UTC, yipliu commented
Hi,

Is there something wrong?

Does it mean I need to use python=3.10.5

2022-06-27 02:05 UTC, ashleve requested changes

2022-06-27 02:05 UTC, ashleve commented on configs/hparams_search/mnist_optuna.yaml
> +  # override the default sampler if you want to try other sampler, such as random for RandomSampler
```suggestion
  # override `tpe` to `random` to execute random search (without optimization)
```

2022-06-27 15:28 UTC, ashleve approved these changes

2022-06-27 15:30 UTC, ashleve commented
LGTM! Thank you!

2022-06-27 15:31 UTC, merged